name = "leca-server"
main = "src/index.js"
compatibility_date = "2024-02-07"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "leca-db"
database_id = "63f179b8-009b-4d83-b939-4b19511e765b"

[vars]
GOOGLE_CLIENT_ID = "92656285781-gecpuf5ug1b75pk8fr4h8dolp4es7a6e.apps.googleusercontent.com"
MP_ACCESS_TOKEN = "APP_USR-1253235899009881-021420-881c35d24b04f32cf875035eeb71fe77-124280008"
